// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/isglb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ISGLBClient is the client API for ISGLB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ISGLBClient interface {
	// When forward path changed, upload the SFUStatus from client to ISGLB
	// When forward path should change, send expected SFUStatus from ISGLB to client
	// Report the communication quality or computation quality of the edge
	SyncSFU(ctx context.Context, opts ...grpc.CallOption) (ISGLB_SyncSFUClient, error)
}

type iSGLBClient struct {
	cc grpc.ClientConnInterface
}

func NewISGLBClient(cc grpc.ClientConnInterface) ISGLBClient {
	return &iSGLBClient{cc}
}

func (c *iSGLBClient) SyncSFU(ctx context.Context, opts ...grpc.CallOption) (ISGLB_SyncSFUClient, error) {
	stream, err := c.cc.NewStream(ctx, &ISGLB_ServiceDesc.Streams[0], "/isglb.ISGLB/SyncSFU", opts...)
	if err != nil {
		return nil, err
	}
	x := &iSGLBSyncSFUClient{stream}
	return x, nil
}

type ISGLB_SyncSFUClient interface {
	Send(*SyncRequest) error
	Recv() (*SFUStatus, error)
	grpc.ClientStream
}

type iSGLBSyncSFUClient struct {
	grpc.ClientStream
}

func (x *iSGLBSyncSFUClient) Send(m *SyncRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *iSGLBSyncSFUClient) Recv() (*SFUStatus, error) {
	m := new(SFUStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ISGLBServer is the server API for ISGLB service.
// All implementations must embed UnimplementedISGLBServer
// for forward compatibility
type ISGLBServer interface {
	// When forward path changed, upload the SFUStatus from client to ISGLB
	// When forward path should change, send expected SFUStatus from ISGLB to client
	// Report the communication quality or computation quality of the edge
	SyncSFU(ISGLB_SyncSFUServer) error
	mustEmbedUnimplementedISGLBServer()
}

// UnimplementedISGLBServer must be embedded to have forward compatible implementations.
type UnimplementedISGLBServer struct {
}

func (UnimplementedISGLBServer) SyncSFU(ISGLB_SyncSFUServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncSFU not implemented")
}
func (UnimplementedISGLBServer) mustEmbedUnimplementedISGLBServer() {}

// UnsafeISGLBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ISGLBServer will
// result in compilation errors.
type UnsafeISGLBServer interface {
	mustEmbedUnimplementedISGLBServer()
}

func RegisterISGLBServer(s grpc.ServiceRegistrar, srv ISGLBServer) {
	s.RegisterService(&ISGLB_ServiceDesc, srv)
}

func _ISGLB_SyncSFU_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ISGLBServer).SyncSFU(&iSGLBSyncSFUServer{stream})
}

type ISGLB_SyncSFUServer interface {
	Send(*SFUStatus) error
	Recv() (*SyncRequest, error)
	grpc.ServerStream
}

type iSGLBSyncSFUServer struct {
	grpc.ServerStream
}

func (x *iSGLBSyncSFUServer) Send(m *SFUStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *iSGLBSyncSFUServer) Recv() (*SyncRequest, error) {
	m := new(SyncRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ISGLB_ServiceDesc is the grpc.ServiceDesc for ISGLB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ISGLB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "isglb.ISGLB",
	HandlerType: (*ISGLBServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncSFU",
			Handler:       _ISGLB_SyncSFU_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/isglb.proto",
}
